<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(2,1,1,'5Lqn5ZOB5LiA57G7');
$cfg_Cs[4]=array(2,1,1,'5Lqn5ZOB5LqM57G7');
$cfg_Cs[5]=array(2,1,1,'5Lqn5ZOB5LiJ57G7');
$cfg_Cs[6]=array(2,1,1,'5Lqn5ZOB5Zub57G7');
$cfg_Cs[7]=array(0,1,1,'6I2j6KqJ6LWE6LSo');
$cfg_Cs[13]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[9]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[10]=array(0,1,1,'55WZ6KiA5Y+N6aaI');
$cfg_Cs[11]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[14]=array(0,1,1,'6aaW6aG15bm754Gv');
$cfg_Cs[15]=array(0,1,1,'5omL5py656uv572R56uZ5Zyw5Zu+');
?>