<?php
$z[0]=Array("field","",54,83);
$z[0][4]['name']="typename";
$z[1]=Array("field","",113,136);
$z[1][4]['name']="id";
$z[2]=Array("arclist","\r\n          <li>\r\n            <div class=\"case_c_pic\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"> </a> </div>\r\n            <div class=\"case_c_content\">\r\n              <h2>[field:title/]</h2>\r\n              <span>[field:description function=\"cn_substr(@me,100)\"/]...</span> </div>\r\n          </li>\r\n          ",208,632);
$z[2][4]['row']="2";
$z[2][4]['orderby']="id";

?>