<?php
$z[0]=Array("field","",56,85);
$z[0][4]['name']="typename";
$z[1]=Array("field","",115,138);
$z[1][4]['name']="id";
$z[2]=Array("arclist","\r\n          <li><a href=\"view.php?aid=[field:id/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\" width=\"240px\" height=\"159px\"> <span class=\"sp1\">[field:title/]</span> </a></li>\r\n          ",246,502);
$z[2][4]['row']="4";
$z[2][4]['orderby']="id";
$z[2][4]['titlelen']="32";

?>