<?php
$z[0]=Array("flink","  [field:link /]  ",211,289);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",407,433);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",455,477);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",499,523);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",682,706);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",708,732);
$z[5][4]['name']="cfg_beian";

?>