<?php
$z[0]=Array("global","",180,206);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n    <li class=\"n_son\"><a href=\"[field:typeurl/]\" title =\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",416,652);
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li class='n_son'><a href='~typelink~'>~typename~</a></li>";
$z[2]=Array("global","",1017,1038);
$z[2][4]['name']="cfg_gg";
$z[3]=Array("global","",1040,1061);
$z[3][4]['name']="cfg_gg";
$z[4]=Array("global","",1254,1279);
$z[4][4]['name']="cfg_cmsurl";

?>