<?php
$z[0]=Array("channel","\r\n        <li class=\"pcla-son\"> <a href='[field:typeurl/]' title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",197,467);
$z[0][4]['type']="son";
$z[0][4]['typeid']="2";
$z[0][4]['currentstyle']="<li class='pcla-son'><a href='~typelink~'>~typename~</a></li>";
$z[1]=Array("global","",776,798);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",828,850);
$z[2][4]['name']="cfg_add";
$z[3]=Array("global","",873,895);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",918,940);
$z[4][4]['name']="cfg_fax";
$z[5]=Array("global","",963,987);
$z[5][4]['name']="cfg_email";
$z[6]=Array("type"," <a href=\"[field:typelink/]\" title = \"查看详情\">查看详细 >></a>",1040,1146);
$z[6][4]['typeid']="12";

?>