<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1250,1285);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1369,1398);
$z[5][4]['name']="position";
$z[6]=Array("field","",1424,1453);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n        <dl class=\"picUl-son\">\r\n          <dt><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" class=\"PicAuto\" width=\"198\" height=\"146\" alt =\"[field:title/]\"  /></a></dt>\r\n          <dd><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></dd>\r\n        </dl>\r\n        ",1641,1991);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2143,2209);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",2294,2329);
$z[9][4]['filename']="left.htm";
$z[10]=Array("include","",2404,2441);
$z[10][4]['filename']="footer.htm";

?>