<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1250,1285);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1369,1398);
$z[5][4]['name']="position";
$z[6]=Array("field","",1424,1453);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n        <li><span class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n        ",1666,1873);
$z[7][4]['pagesize']="15";
$z[8]=Array("pagelist","",1990,2056);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",2134,2169);
$z[9][4]['filename']="left.htm";
$z[10]=Array("include","",2244,2281);
$z[10][4]['filename']="footer.htm";

?>